### ISSUE TITLE
Individual Function Ideas

### ISSUE THREAD

**Issue by salva-u** [UBC-MDS/Pythoshop#1]

**Comment by salva-u** [comment]
Uniform Aspect Ratio function: which will take images dataset as input as input in addition to the below parameters
input parameters:
1.  height, width of all images ,
2. method of obtaining the desired image dimensions : crop, scaling, etc.

Based on the method inputted to the function, will crop all images to the same dimensions or resize/scale the images to the same dimensions.

May add additional functionality to function later on.

Reference:
https://becominghuman.ai/image-data-pre-processing-for-neural-networks-498289068258

**Comment by Rachel0619** [comment]
Adjust Brightness: Adjusting the brightness of an image to make it brighter or darker. It can be used to improve the visibility of images taken in poor lighting conditions. 

Possible input parameters of the function (might add more optional parameters if we have extra time)

- Image Data: .jpg or .png files
- Brightness Adjustment Factor: determines how much to adjust the brightness. It can be a positive (increase brightness) or negative (decrease brightness) value. data type: int or float (TBD: depends on whether it's a numeric value that gets added to or subtracted from each pixel value or it's a percentage indicating how much to brighten or darken the image) 

Output:  .png file 

Might need to import PIL or OpenCV for transforming the .jpg or .png files into 3D numpy arrays (representing the pixel values)

**Comment by jlee2843** [comment]
Apply filter to the image: Adjusting the color scheme of the image. For example, we could apply _blue_ or _brown_ filter across the image. 
**Input parameters:**
- Image data
- Methods, deciding which color filter to apply.
- To which degree, how strong you want the filter to be.

Output: .png file.
Reference: 
- https://levelup.gitconnected.com/apply-filters-to-images-with-python-in-less-than-20-lines-of-code-5bc14ac0ceca
- https://medium.com/@parasraorane/image-manipulation-in-python-without-external-libraries-8a7996b1155a

**Comment by ella-irene** [comment]
Transform Image: Rotate or flip an image in a desired direction.

Possible input params:
- Image
- Tranformation type: flip or rotate
- Direction: Vertical, horizontal, clockwise, counterclockwise

Output: .png

**Comment by salva-u** [comment]
@Rachel0619 identified we need to have 2 additional helper functions for loading images and exporting the final images.

**Comment by salva-u** [comment]
we can omit the helper functions if we go with matlplotlib for loading
