### ISSUE TITLE
Best Practice

### ISSUE THREAD

**Issue by Rachel0619** [UBC-MDS/Pythoshop#15]
When labelling the commits:

“build”: indicates a change to the build system or external dependencies.
“docs”: indicates a change to documentation.
“feat”: indicates a new feature being added to the code base.
“fix”: indicates a bug fix.
“test”: indicates changes to testing framework.

**Comment by salva-u** [comment]
all taken into account

**Comment by Rachel0619** [comment]
Reopened the issue cuz I think it's better to keep it open for future reference during the whole session of our project.  I think we also have some other best practice to be added as we move forward. Guys what do you think?

**Comment by jlee2843** [comment]
After you do a `git pull`, make sure you also do `poetry install`.

**Comment by Rachel0619** [comment]
Do code review on github before you approve the pull request.

**Comment by Rachel0619** [comment]
We'd better build our own .py file per function inside the src folder since basically our functions are doing separate tasks and this will help reducing possible merge conflict.

**Comment by ella-irene** [comment]
Hi all, for our tests I noticed that not all of us are adding the if ```__name__ == '__main__': ``` to the bottom of our files. It might be nice to standardize this, as my group got a few comments on it in the last block. Comment your thoughts.

**Comment by salva-u** [comment]
All function and testing is now complete, will reopen for next milestone
