### ISSUE TITLE
Ideas for Packages

### ISSUE THREAD

**Issue by jlee2843** [UBC-MDS/Pythoshop#3]
| **Idea** | **Description** |
| --- | --- | 
| Data Visualization  | Visualizing chemistry data or geo mapping (GIS-esque) |
| Image Processing | Cropping image, flipping image, changing colors / adding filters |
| EDA Package | Auto-checks data types, outputs histograms, missing values, ect.  |
| Natural Language Processing | Detect the most frequent words and count the frequency, sentiment analysis…, Create a summary of the text if the text is long enough.  |
| Video Processing |  Video trimming and count the number of frames.  |
| Dynamic Visualization |  Showing statistical changes over time (ie programming language usage, health data, followers, stock market values, ect.). Could output different types of dynamic graphs (boxplots, area charts, maps, ect.)  |

**Comment by salva-u** [comment]
Based on team voting, we picked Option 2
