### ISSUE TITLE
Week 2 MOM

### ISSUE THREAD

**Issue by ella-irene** [UBC-MDS/Pythoshop#35]
Tasks for everyone:
1. Approve and merge Salva's PR from pair programming to MAIN
3. Build out each of our individual functions
5. Write 1 test per function (each written as a class, using pytest)

Individual tasks:
- Update readme: @Rachel0619 
- Update changelog: @jlee2843 
- Adding main branch protection: @salva-u 

Notes from class:
Run poetry install every time you pull

**Comment by salva-u** [comment]
Added main branch protection

**Comment by ella-irene** [comment]
Next steps:
1. Update readme with Salva's updated function name.
2. Each only submit one PR which includes both the test file and the function file.
4. Merge all PR's.
5. Individually add to example file once all function PR's are merged.
6. Meet on Slack tmrw @3:00 to go over final details and submit (fingers crossed).
