### ISSUE TITLE
Milestone 3 MOM

### ISSUE THREAD

**Issue by jlee2843** [UBC-MDS/Pythoshop#63]
For **Milestone 3**
- Finish documentations: make the examples more in detail.
- Each person is responsible for polishing their own examples.
- All documentation will be recorded on the same file. 
- Watch out for possible conflicts. 

**Changes in Plan**
- If the quiz is moved to Thursday, Thursday meeting will not be happening. 
- If decide to use the workflow (will be covered on lecture 6), meet on Saturday to test out together. 
   - Anyone who volunteers to try it out first is welcomed.

**Comment by salva-u** [comment]
Additional possible tasks :
- See if we wanna change the theme a bit, add the changelog etc under Developer notes ( we can follow what she showed us in the notes?) looks cleaner
- Ensure the python version and toml packages are write (ensure toml file and lock files are in sync and looking good )
- Could go in cleanup branch: Delete the requirements file, add logo, update the readme, add the readthedocs button in readme as mentioned by tiff
- Someone should add the secrets, etc before next lab , we have branch protection so there is a token for that too ( I thinkk GITHUB_TOKEN)

**Comment by ella-irene** [comment]
Notes from discussion Friday, Jan 26:
- Update readme and delete requirements: @ella-irene 
- Add motivation and introduction: @Rachel0619 
- readthedocs: @jlee2843 
- Add token: @ella-irene

**Comment by salva-u** [comment]
all points addressed
