### ISSUE TITLE
Two helper functions except from our four functions

### ISSUE THREAD

**Issue by Rachel0619** [UBC-MDS/Pythoshop#7]
We would need two helper functions for the package:

- transform image file to 3D numpy array
- transform 3D numpy array back to image file

TBD: whether we should limit the input image type to only png?

**Comment by Rachel0619** [comment]
It would be something like these:

With Pillow:

```
from PIL import Image
import numpy as np

def load_image_as_numpy_array(file_path):
    # Open the image file
    with Image.open(file_path) as img:
        # Convert the image to RGB (if not already in this format)
        img = img.convert('RGB')
        # Convert the image to a numpy array
        numpy_array = np.array(img)
    return numpy_array
```


With OpenCV:

```
import cv2

def load_image_as_numpy_array(file_path):
    # Read the image
    # cv2.imread by default reads images in BGR format
    img = cv2.imread(file_path, cv2.IMREAD_COLOR)
    # Convert BGR to RGB
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    return img
```

**Comment by Rachel0619** [comment]
i would put these two functions in the pythoshop.py file for now. If we think it's better to be moved to other folders, we can change it later.

**Comment by salva-u** [comment]
Hey guys I just checked our old labs for 512, just to keep it simple we can use matplotlib to read the image, it will store it in the way that we need to edit our image, change colors etc, we do not need additional dependencies for our package:
 To read an image:
```
mandrill = plt.imread("mandrill.jpg")
plt.imshow(mandrill);
```
The type of the mandrill variable above would be numpy array which is what we want.
type(mandrill)

Example manipulation:
```
mandrill2 = mandrill.copy()
blue_channel = mandrill[:, :, 2].copy()
green_channel = mandrill[:, :, 1].copy()
red_channel = mandrill[:, :, 0].copy()
mandrill2[:,:,0] = green_channel
mandrill2[:,:,1] = red_channel
plt.imshow(mandrill2);
```

Export :
```
plt.imsave("logo.png", img, cmap = 'gray', origin = 'lower')
```

**Comment by salva-u** [comment]
Let's go with this, let's use matplotlib?
https://www.geeksforgeeks.org/working-with-images-in-python-using-matplotlib/

**Comment by Rachel0619** [comment]
Cool. I personally down to using matplotlib

**Comment by ella-irene** [comment]
Sounds good to me! Better to minimize the number of dependencies.
