### ISSUE TITLE
Should we import PIL or OpenCV to do some basic image transformation?

### ISSUE THREAD

**Issue by Rachel0619** [UBC-MDS/Pythoshop#9]
Writing a function to load an image as a NumPy array from scratch is quite challenging. This is because image files (such as JPEG, PNG, etc.) are typically stored in formats that require complex decoding processes. These formats often include compression, color space conversions, and various other considerations.

After doing some basic research, there are two popular packages out there named PIL and OpenCV that we would like to import as our dependencies.  It would be less error-prone and more robust to use this packages for transformming between png file and numpy arrays so that we can focus on the main tasks of our package. 

Should we do this? Let's discuss😊

**Comment by jlee2843** [comment]
I personally am positive that we can use these packages, as using the function to load the images isn't too complicated and it's not one of our main functions that `Pythoshop` offers. However, it might be better to use our own hand-crafted image loading function if we want to unite everything together (e.g., use same image loading function for all our other tasks.) I'm open to both.

**Comment by salva-u** [comment]
@Rachel0619 could you share the code you mentioned we could use, I guess we can create the 2 helper functions that we all use as @jlee2843 also said, I guess PIL is simpler, should we go with that ?

**Comment by salva-u** [comment]
refer to issue regarding importing using matplotlib
