### ISSUE TITLE
Things need to be fixed for milestone 4

### ISSUE THREAD

**Issue by Rachel0619** [UBC-MDS/Pythoshop#96]
1. Add badges for the project in the README.md
2. Changed the version constraints for project.toml file

**Comment by salva-u** [comment]
Refer to Peer Review Points that need to be updated

**Comment by salva-u** [comment]
- Project toml version @Rachel0619 
- Use [Fix: peer review - to be added](fix: Feedback addressed by ...) --> commit messages should look like this
- Add the new license @Rachel0619 @salva-u 
- Workflow : double check that it works and debug issues @salva-u @jlee2843

**Comment by salva-u** [comment]
- New license added
- Toml Version fixed 
- Workflow fixed

**Comment by salva-u** [comment]
done
